mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^accounts/', include('accounts.urls')),
    url(r'^timentor/', include('timentor.urls')),
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
]

polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'
urlpatterns = [
        url(r'^$', views.IndexView.as_view(), name='index'),
        # ex: /polls/5/
        url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name="detail"),
        # ex: /polls/5/results/
        url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name="results"),
        # ex: /polls/5/vote/
        url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name="vote"),
]

timentor/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login, logout

from timentor.forms import LoginForm
from . import views

app_name = 'timentor'
urlpatterns = [
    # url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^login/$', login, {'template_name': 'timentor/login.html', 'authentication_form': LoginForm}, name='login'),
    url(r'^logout/$', logout, {'template_name': 'timentor/login.html'}, name='logout'),
    url(r'^main/$', views.main, name='main'),
    url(r'^main/child_tasks/(?P<task_no>[0-9]+)/$', views.main_child_tasks, name='main_child_tasks'),
    url(r'^new_todo/$', views.new_todo_parent, name='new_todo_parent'),
    url(r'^new_todo/(?P<task_date>[0-9]+)/(?P<task_no>[0-9]+)/$', views.new_todo_child, name='new_todo_child'),
    url(r'^list/daily/(?P<task_date>[0-9]+)/edit$', views.list_daily_edit, name="list_daily_edit"),
    url(r'^list/daily/(?P<task_date>[0-9]+)/(?P<task_no>[0-9]+)/edit$',
        views.list_daily_task_edit, name="list_daily_task_edit"),
]

timentor/models.py
from django.db import models
from django.core.validators import MaxValueValidator
from django.utils.timezone import datetime


class Task(models.Model):
    TASK_NO_CHOICES = (
        (1, 1), (2, 2), (3, 3), (4, 4), (5, 5),
        (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)
    )
    TIME_CHOICES = (
        ('0.5', '0.5'), ('1', '1'), ('1.5', '1.5'), ('2', '2'), ('2.5', '2.5'), ('3', '3'),
        ('3.5', '3.5'), ('4', '4'), ('4.5', '4.5'), ('5', '5'), ('6', '6'), ('7', '7')
    )
    TIME_START_AND_END_CHOICES = (
        ('3.5', '3:30'), ('4', '4:00'), ('4.5', '4:30'), ('5', '5:00'), ('5.5', '5:30'), ('6', '6:00'), ('6.5', '6:30'),
        ('7', '7:00'), ('7.5', '7:30'), ('8', '8:00'), ('8.5', '8:30'), ('9', '9:00'), ('9.5', '9:30'), ('10', '10:00'),
        ('10.5', '10:30'), ('11', '11:00'), ('11.5', '11:30'), ('12', '12:00'), ('12.5', '12:30'), ('13', '13:00'),
        ('13.5', '13:30'), ('14', '14:00'), ('14.5', '14:30'), ('15', '15:00'), ('15.5', '15:30'), ('16', '16:00'),
        ('16.5', '16:30'), ('17', '17:00'), ('17.5', '17:30'), ('18', '18:00'), ('18.5', '18:30'), ('19', '19:00'),
        ('19.5', '19:30'), ('20', '20:00'), ('20.5', '20:30'), ('21', '21:00'), ('21.5', '21:30'), ('22', '22:00'),
        ('22.5', '22:30')
    )
    task_no = models.IntegerField("No.", validators=[MaxValueValidator(10)], choices=TASK_NO_CHOICES)
    task_name = models.CharField("Task Name", max_length=256, blank=False)
    time = models.CharField("Time", blank=False, max_length=3, choices=TIME_CHOICES)
    time_start = models.CharField("From", max_length=5, choices=TIME_START_AND_END_CHOICES)
    time_end = models.CharField("To", max_length=5, choices=TIME_START_AND_END_CHOICES)
    time_started = models.IntegerField(blank=True, null=True)
    time_ended = models.IntegerField(blank=True, null=True)
    create_date = models.DateTimeField
    update_date = models.DateTimeField

    class Meta:
        abstract = True

    def __str__(self):
        return self.task_name


class ParentTask(Task):
    today = datetime.now().strftime("%Y/%m/%d")
    task_date = models.CharField("Date", max_length=10, default=today)


class ChildTask(Task):
    parent_task = models.ForeignKey(ParentTask, verbose_name="Task for", blank=True, null=True)
    classification = models.CharField(max_length=256, verbose_name="Tag")

timentor/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.forms import ModelForm
from django.forms.formsets import BaseFormSet
from .models import ParentTask, ChildTask


class RegisterForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['class'] = 'form-control'
        self.fields['sex'].widget.attrs['class'] = 'form-control'


class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['password'].widget.attrs['class'] = 'form-control'


class ParentTaskForm(ModelForm):
    class Meta:
        model = ParentTask
        fields = [
            'task_date', 'task_no', 'task_name', 'time', 'time_start', 'time_end', 'time_started', 'time_ended',
        ]


class ChildTaskForm(ModelForm):
    class Meta:
        model = ChildTask
        fields = [
            'task_no', 'task_name', 'time', 'time_start', 'time_end', 'time_started', 'time_ended',
            'classification', 'parent_task'
        ]


class BaseTaskFormSet(BaseFormSet):
    def clean(self):
        """
        Adds validation to check that no two tasks with the same task name are submitted
        :return:
        """
        if any(self.errors):
            return

        task_names = []
        for form in self.forms:
            task_name = form['task_name'].value()
            if task_name in task_names:
                raise forms.ValidationError("Task Name must be unique")
            task_names.append(task_name)
        return self.forms

timentor/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.urls import reverse
from django.views import generic
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from .forms import RegisterForm, ParentTaskForm, ChildTaskForm, BaseTaskFormSet
from .models import ChildTask, ParentTask
from django.forms import formset_factory
from django.utils.timezone import datetime
from django.contrib import messages
from django.shortcuts import get_list_or_404, get_object_or_404


def main(request):
    today = datetime.now().strftime("%Y/%m/%d")
    try:
        parent_tasks = ParentTask.objects.filter(task_date=today)
    except ParentTask.DoesNotExist:
        error_message = today + "'s task does not exist"
        return render(request, 'timentor/main.html', {'today': today,
                                                      'error_message': error_message})
    return render(request, 'timentor/main.html', {'parent_tasks': parent_tasks,
                                                  'today': today})


def main_child_tasks(request, task_no):
    today = datetime.now().strftime("%Y/%m/%d")
    parent_task = get_object_or_404(ParentTask, task_date=today, task_no=task_no)
    child_tasks = get_list_or_404(ChildTask, parent_task=parent_task)
    if request.method == 'POST':
        parent_task = ParentTask(id=parent_task.id, task_no=parent_task.task_no, task_date=parent_task.task_date,
                                 time=parent_task.time, time_start=parent_task.time_start, time_end=parent_task.time_end,
                                 task_name=parent_task.task_name, time_started=request.POST['started'])
        parent_task.save()
    return render(request, 'timentor/main_child_tasks.html', {
        'child_tasks': child_tasks,
        'parent_task': parent_task
    })


def new_todo_parent(request):
    ParentTaskFormSet = formset_factory(ParentTaskForm, formset=BaseTaskFormSet)
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        formset = ParentTaskFormSet(request.POST)
        if formset.is_valid():
            for form in formset:
                cd = form.cleaned_data
                parent_task = ParentTask(task_date=cd['task_date'], task_no=cd['task_no'], task_name=cd['task_name'],
                                         time=cd['time'], time_start=cd['time_start'], time_end=cd['time_end'])
                parent_task.save()
            messages.success(request, 'You have created the tasks')
            task_date_string = "".join(parent_task.task_date.split("/"))
            return HttpResponseRedirect(reverse('timentor:list_daily_edit', args=(task_date_string,)))
        else:
            print(formset.errors)
            messages.error(request, "You have something wrong with the tasks you made")
            return HttpResponseRedirect(reverse('timentor:new_todo_parent'))
    else:
        formset = ParentTaskFormSet(initial=[
            {'task_date': datetime.now().strftime("%Y/%m/%d")}
        ])
    return render(request, 'timentor/new_todo_parent.html', {'formset': formset})


def new_todo_child(request, task_date, task_no):
    task_date_string = task_date[:4] + "/" + task_date[4:6] + "/" + task_date[6:]
    daily_task_with_task_no = get_object_or_404(ParentTask, task_date=task_date_string, task_no=task_no)
    ChildTaskFormSet = formset_factory(ChildTaskForm, formset=BaseTaskFormSet)
    if request.method == 'POST':
        formset = ChildTaskFormSet(request.POST)
        if formset.is_valid():
            for form in formset:
                cd = form.cleaned_data
                child_task = ChildTask(task_no=cd['task_no'], task_name=cd['task_name'], time=cd['time'],
                                       time_start=cd['time_start'], time_end=cd['time_end'],
                                       classification=cd['classification'], parent_task=daily_task_with_task_no)
                child_task.save()
                return HttpResponseRedirect(reverse('timentor:list_daily_task_edit', args=(task_date, task_no)))
        else:
            messages.error(request, "You have something wrong with the tasks you made")
            return HttpResponseRedirect(reverse('timentor:new_todo_child'))
    else:
        formset = ChildTaskFormSet()
    return render(request, 'timentor/new_todo_child.html', {
        'formset': formset,
        'parent_task': daily_task_with_task_no,
        })


def list_daily_edit(request, task_date):
        task_date_string = task_date[:4] + "/" + task_date[4:6] + "/" + task_date[6:]
        parent_tasks = get_list_or_404(ParentTask, task_date=task_date_string)
        return render(request, 'timentor/list_daily_edit.html', {
            'parent_tasks': parent_tasks,
            'task_date': task_date
            })


def list_daily_task_edit(request, task_date, task_no):
    task_date_string = task_date[:4] + "/" + task_date[4:6] + "/" + task_date[6:]
    parent_task = get_object_or_404(ParentTask, task_date=task_date_string, task_no=task_no)
    child_tasks = get_list_or_404(ChildTask, parent_task=parent_task)
    return render(request, 'timentor/list_daily_task_edit.html', {
        'child_tasks': child_tasks,
        'parent_task': parent_task
    })

timentor/templates/timentor/list_daily_edit.html
{% extends "./common/base.html" %}

{% block title %}Create Child Task{% endblock %}

{% block content %}
    <h1>The task for {{ task_date }}</h1>
    <table>
        <tbody>
            <tr>
                <td>No.</td>
                <td>Task Name</td>
                <td>Time</td>
                <td>From</td>
                <td>To</td>
            </tr>
            {% for task in parent_tasks %}
            <tr>
                <td>{{ task.task_no }}</td>
                <td>{{ task.task_name }}</td>
                <td>{{ task.time }}</td>
                <td>{{ task.get_time_start_display }}</td>
                <td>{{ task.get_time_end_display }}</td>
                <td><a href="{% url 'timentor:new_todo_child' task_date task.task_no %}">
                    Add child task</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

timentor/templates/timentor/list_daily_task_edit.html
{% extends "./common/base.html" %}

{% block content %}
 {% load static %}
    {% if messages %}
        {% for message in messages %}
            <p>{{ message }}</p>
        {% endfor %}
    {% endif %}
    <table>
        <caption>Parent Task</caption>
        <tbody>
            <tr>
                <td>Task Date</td>
                <td>No.</td>
                <td>Task Name</td>
                <td>Time</td>
                <td>From</td>
                <td>To</td>
            </tr>
            <tr>
                <td>{{ parent_task.task_date }}</td>
                <td>{{ parent_task.task_no }}</td>
                <td>{{ parent_task.task_name }}</td>
                <td>{{ parent_task.time }}</td>
                <td>{{ parent_task.get_time_start_display }}</td>
                <td>{{ parent_task.get_time_end_display }}</td>
            </tr>
        </tbody>
    </table>
    <form>
        <table>
            <caption>Child Tasks</caption>
            <tbody>
                <tr>
                    <td>No.</td>
                    <td>Task Name</td>
                    <td>Time</td>
                    <td>From</td>
                    <td>To</td>
                    <td>Classification</td>
                </tr>
                {% for task in child_tasks %}
                <tr>
                    <td>{{ task.task_no }}</td>
                    <td>{{ task.task_name }}</td>
                    <td>{{ task.time }}</td>
                    <td>{{ task.time_start }}</td>
                    <td>{{ task.get_time_end_display }}</td>
                    <td>{{ task.classification }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </form>
{% endblock %}

timentor/templates/timentor/login_top.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login Top</title>
</head>
<body>

    <form method="post" action="{% url 'timentor:login' %}">
        {% csrf_token %}
        <label for="login_email">Email</label>
        <input type="text" name="login_email" id="login_email" /><br/>

        <label for="login_password">Password</label>
        <input type="password" name="login_password" id="login_password" /><br/>

        <input type="submit" value="Login" />
    </form>

</body>
</html>

timentor/templates/timentor/main.html
{% extends "./common/base.html" %}

{% block title %}Create Child Task{% endblock %}

{% block content %}
<h1>{{ today }}'s tasks</h1>
<table>
    <tbody>
        <tr>
            <td>No.</td>
            <td>Task Name</td>
            <td>Time</td>
            <td>From</td>
            <td>To</td>
        </tr>
        {% for task in parent_tasks %}
        <tr>
            <td>{{ task.task_no }}</td>
            <td>{{ task.task_name }}</td>
            <td>{{ task.time }}</td>
            <td>{{ task.get_time_start_display }}</td>
            <td>{{ task.get_time_end_display }}</td>
            <td><a href="{% url 'timentor:main_child_tasks' task.task_no %}">
                Go!</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

timentor/templates/timentor/main_child_task.html
{% extends "./common/base.html" %}

{% block title %}Create Child Task{% endblock %}

{% block content %}
<table>
    <caption>Parent Task</caption>
    <tbody>
        <tr>
            <td>No.</td>
            <td>Task Name</td>
            <td>Time</td>
            <td>From</td>
            <td>To</td>
        </tr>
        <tr>
            <td>{{ parent_task.task_no }}</td>
            <td>{{ parent_task.task_name }}</td>
            <td>{{ parent_task.time }}</td>
            <td>{{ parent_task.time_start }}</td>
            <td>{{ parent_task.time_end }}</td>
        </tr>
    </tbody>
</table>

<table>
    <caption>Child Tasks</caption>
    <tbody>
        <tr>
            <td>No.</td>
            <td>Task Name</td>
            <td>Time</td>
            <td>From</td>
            <td>To</td>
        </tr>
        {% for task in child_tasks %}
        <tr>
            <td>{{ task.task_no }}</td>
            <td>{{ task.task_name }}</td>
            <td>{{ task.time }}</td>
            <td>{{ task.time_start}}</td>
            <td>{{ task.time_end }}</td>
        </tr>
    </tbody>
</table>

{% endblock %}

timentor/templates/timentor/main_child_tasks.html
{% extends "./common/base.html" %}

{% block title %}Create Child Task{% endblock %}

{% block content %}
<table>
    <caption>Parent Task</caption>
    <tbody>
        <tr>
            <td>No.</td>
            <td>Task Name</td>
            <td>Time</td>
            <td>From</td>
            <td>To</td>
            <td>Start</td>
            <td>End</td>
        </tr>
        <tr>
            <td>{{ parent_task.task_no }}</td>
            <td>{{ parent_task.task_name }}</td>
            <td>{{ parent_task.time }}</td>
            <td>{{ parent_task.get_time_start_display }}</td>
            <td>{{ parent_task.get_time_end_display }}</td>
            <form method="post" action="">
                {% csrf_token %}
                <input type="hidden" name="started" value="0">
                <td><input type="submit" value="Start"/></td>
                <td><button>End</button></td>
            </form>
        </tr>
    </tbody>
</table>

<table>
    <caption>Child Tasks</caption>
    <tbody>
        <tr>
            <td>No.</td>
            <td>Task Name</td>
            <td>Time</td>
            <td>From</td>
            <td>To</td>
            <td>Start</td>
            <td>End</td>
        </tr>
        {% for task in child_tasks %}
        <tr>
            <td>{{ task.task_no }}</td>
            <td>{{ task.task_name }}</td>
            <td>{{ task.time }}</td>
            <td>{{ task.get_time_start_display }}</td>
            <td>{{ task.get_time_end_display }}</td>
            <td><button>Start</button></td>
            <td><button>End</button></td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

timentor/templates/timentor/new_todo_child.html
{% extends "./common/base.html" %}

{% load static %}

{% block content %}
    {% if messages %}
        {% for message in messages %}
            <p>{{ message }}</p>
        {% endfor %}
    {% endif %}
    <table>
        <caption>Parent Task</caption>
        <tbody>
            <tr>
                <td>Task Date</td>
                <td>No.</td>
                <td>Task Name</td>
                <td>Time</td>
                <td>From</td>
                <td>To</td>
            </tr>
            <tr>
                <td>{{ parent_task.task_date }}</td>
                <td>{{ parent_task.task_no }}</td>
                <td>{{ parent_task.task_name }}</td>
                <td>{{ parent_task.time }}</td>
                <td>{{ parent_task.time_start }}</td>
                <td>{{ parent_task.time_end }}</td>
            </tr>
        </tbody>
    </table>

    <form id="new_todo_list" method="post" action="">
        {% csrf_token %}
        {{ formset.management_form }}
        <table>
            <caption>Child Tasks</caption>
            <tbody>
                <tr>
                    <td>No.</td>
                    <td>Task Name</td>
                    <td>Time</td>
                    <td>From</td>
                    <td>To</td>
                    <td>Classification</td>
                </tr>
                {% for form in formset %}
                <tr class="value_row">
                    <td>{{ form.task_no }}</td>
                    <td>{{ form.task_name }}
                        {% if form.task_name.errors %}
                            {% for error in form.task_name.errors %}
                                {{ error|escape }}
                            {% endfor %}
                        {% endif %}
                    </td>
                    <td>{{ form.time }}
                        {% if form.time.errors %}
                            {% for error in form.time.errors %}
                                {{ error|escape }}
                            {% endfor %}
                        {% endif %}
                    </td>
                    <td>{{ form.get_time_start_display }}</td>
                    <td>{{ form.get_time_end_display }}</td>
                    <td>{{ form.classification }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <input type="submit" value="create new tasks" class="button" />
    </form>


    <!-- Include formset plugin - including jQuery dependency -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="{% static 'timentor/js/jquery.formset.js' %}"></script>
    <script src="{% static 'timentor/js/change_time.js' %}"></script>
    <script src="{% static 'timentor/js/add_elements.js' %}"></script>
    <script type="text/javascript">
            $('#new_todo_list .value_row').formset({
                addText: 'add task',
                deleteText: 'delete'
            });
    </script>
{% endblock %}

timentor/templates/timentor/new_todo_parent.html
{% extends "./common/base.html" %}

{% load static %}

{% block content %}

    {% if messages %}
        {% for message in messages %}
            <p>{{ message }}</p>
        {% endfor %}
    {% endif %}
    <form id="new_todo_list" method="post" action="">
        {% csrf_token %}
        {{ formset.management_form }}
        <table>
            <tbody>
                <tr>
                    <td>Task Date</td>
                    <td>No.</td>
                    <td>Task Name</td>
                    <td>Time</td>
                    <td>From</td>
                    <td>To</td>
                </tr>
                {% for form in formset %}
                <tr class="value_row">
                    <td>{{ form.task_date }}
                        {% if form.task_date.errors %}
                            {% for error in form.task_date.errors %}
                                {{ error|escape }}
                            {% endfor %}
                        {% endif %}
                    </td>
                    <td>{{ form.task_no }}</td>
                    <td>{{ form.task_name }}
                        {% if form.task_name.errors %}
                            {% for error in form.task_name.errors %}
                                {{ error|escape }}
                            {% endfor %}
                        {% endif %}
                    </td>
                    <td>{{ form.time }}
                        {% if form.time.errors %}
                            {% for error in form.time.errors %}
                                {{ error|escape }}
                            {% endfor %}
                        {% endif %}
                    </td>
                    <td>{{ form.time_start }}</td>
                    <td>{{ form.time_end }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <input type="submit" value="create new tasks" class="button" />
    </form>


    <!-- Include formset plugin - including jQuery dependency -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="{% static 'timentor/js/jquery.formset.js' %}"></script>
    <script src="{% static 'timentor/js/change_time.js' %}"></script>
    <script src="{% static 'timentor/js/add_elements.js' %}"></script>
    <script type="text/javascript">
            $('#new_todo_list .value_row').formset({
                addText: 'add task',
                deleteText: 'delete'
            });
    </script>
{% endblock %}